#!/bin/bash

mkdir build && cd build \
&& cmake \
  -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain.cmake \
  -DCMAKE_INSTALL_PREFIX=/opt/install \
  -DCMAKE_BUILD_TYPE=Release \
  -DJSONCPP_WITH_TESTS=OFF \
  -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF\
  .. \
&& make install \
&& mv /opt/install/include/json /opt/install/include/jsoncpp
