FROM ricejasonf/emscripten AS cctools

# cctools (linker for darwin targets)
RUN git clone https://github.com/tpoechtrager/cctools-port.git \
  && cd cctools-port/cctools \
  && ./configure \
  && make \
  && make install
  
FROM ubuntu:artful

COPY ./toolchain/tvossimulator.cmake /opt/toolchain.cmake
COPY --from=cctools /usr/local /usr/local
