FROM ricejasonf/emscripten AS cctools

# cctools (linker for darwin targets)
RUN git clone https://github.com/tpoechtrager/cctools-port.git \
  && cd cctools-port/cctools \
  && ./configure --prefix /opt/install \
  && make \
  && make install
  
FROM ubuntu:artful

COPY cppdock /usr/local/bin
COPY recipes/ /root/.cppdock_recipes
COPY ./toolchain/tvossimulator.cmake /opt/toolchain.cmake
COPY --from=cctools /opt/install /usr/local
