FROM ricejasonf/cppdock:linux_x64 AS base_image
  RUN apt-get update -yq && apt-get install -yq nodejs npm

FROM base_image AS build_binaryen
  WORKDIR /opt/src
  RUN git clone --depth=1 --branch version_125 \
    https://github.com/WebAssembly/binaryen.git
  WORKDIR /opt/build
  RUN cmake -DCMAKE_TOOLCHAIN_FILE=/opt/cppdock/toolchains/linux_x64.cmake \
            -DBUILD_TESTS=OFF \
            -DCMAKE_INSTALL_PREFIX=/opt/install \
            /opt/src/binaryen && \
    make -j$(nproc) && make install

FROM base_image AS build_emscripten
  WORKDIR /opt/src
  RUN git clone --depth=1 --branch 4.0.20 \
    https://github.com/emscripten-core/emscripten
  WORKDIR /opt/src/emscripten
  RUN ./tools/maint/create_entry_points.py && \
      ./tools/install.py /opt/install/emscripten
  
FROM base_image
  COPY cppdock /usr/local/bin/
  COPY recipes/ /opt/cppdock/recipes
  COPY toolchains/ /opt/cppdock/toolchains
  COPY --from=build_binaryen /opt/install/ /usr/local
  COPY --from=build_emscripten /opt/install/ /usr/local
  WORKDIR /usr/local/emscripten
  RUN ./emcc --generate-config && ./emcc --check && ./embuilder.py build MINIMAL
  # Copy heavy-scheme libraries
  COPY --from=base_image /opt/sysroot/include/heavy/*.sld ./cache/sysroot/include/heavy/
  COPY --from=base_image /opt/sysroot/include/heavy/base/*.sld ./cache/sysroot/include/heavy/base/
  RUN ln -snf /usr/local/emscripten/cache/sysroot/ /opt/sysroot
  ENV EMSCRIPTEN_ROOT=/usr/local/emscripten
